---
replicaCount: 1

image:
  repository: gcr.io/${GOOGLE_PROJECT_ID}/webbb
  tag: ${CIRCLE_SHA1}
  pullPolicy: Always

service:
  type: NodePort
  port: 8080

app_port: 49160
environment: production
