version: 2.1
jobs:
  build:
    machine: true
    steps:
     - checkout
     - run: 
         name: build
         command: |
           docker build -t webbb .
           docker save webbb:latest | gzip > webbb_latest.tar.gz
     - persist_to_workspace:
         root: ./
         paths:
             - ./
  push:
    docker:
      - image: google/cloud-sdk
        auth:
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
     - attach_workspace:
         at: ./
      - setup_remote_docker:
          version: 20.10.6
     - run:
         name: push in gcr
         command: |
           echo " { \"type\": \"service_account\", 
           \"private_key_id\": \"$GCLOUD_PRIVATE_KEY_ID\", 
           \"private_key\": \"$GCLOUD_SERVICE_KEY\", 
           \"client_email\": \"$GOOGLE_EMAIL\",
           \"client_id\": \"$CLIENT_ID\",
           \"auth_uri\": \"https://accounts.google.com/o/oauth2/auth\",
           \"token_uri\": \"https://oauth2.googleapis.com/token\", 
           \"auth_provider_x509_cert_url\": \"https://www.googleapis.com/oauth2/v1/certs\", 
           \"client_x509_cert_url\": \"$GCP_AUTH_X509\" } " >cred.json
           gcloud auth activate-service-account --key-file=cred.json
           gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
           gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
           cd ${HOME}/project
           docker load -i ${HOME}/project/webbb_latest.tar.gz
           docker tag webbb:latest eu.gcr.io/${GOOGLE_PROJECT_ID}/webbb:${CIRCLE_SHA1}
           gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://eu.gcr.io
           docker push eu.gcr.io/${GOOGLE_PROJECT_ID}/webbb:${CIRCLE_SHA1}
     - persist_to_workspace:
        root: ./
        paths:
            - ./
  deploy:
    machine: true
    steps:
      - attach_workspace:
         at: ./
      - run:
          name: simple deployment
          command: |
            gcloud auth activate-service-account --key-file=cred.json
            echo "Done"
            sleep 5
            gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
            echo "Done"
            sleep 5
            gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
            echo "Done"
            sleep 5
            echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee -a /etc/apt/sources.list.d/kubernetes.list
            sudo apt update
            sudo apt-get install -y kubectl
            gcloud container clusters get-credentials my_gke_cluster
            wget https://get.helm.sh/helm-v3.6.3-linux-amd64.tar.gz
            tar -zxvf helm-v3.6.3-linux-amd64.tar.gz
            sudo mv linux-amd64/helm /usr/local/bin/helm
            pwd
            sleep 10
            ls
workflows:
  version: 2.1
  build_push_and_deploy:
    jobs:
      - build:
         filters:
           branches:
             only: master
      - push:
         context:
           - gcp
         requires:
           - build
      - deploy:
         context:
           - gcp
         requires:
           - build
           - push