version: 2
jobs:
  build:
    machine: true
    steps:
     - checkout
     - run: 
         name: build
         command: |
           docker build -t webbb .
           docker save webbb:latest | gzip > webbb_latest.tar.gz
     - persist_to_workspace:
         root: ./
         paths:
             - ./
  push:
    docker:
      - image: google/cloud-sdk
    steps:
     - attach_workspace:
         at: ./
     - setup_remote_docker:
          version: 20.10.6
     - run:
         name: push in gcr
         command: |
           echo "$GCLOUD_ACC" | base64 -d | docker login -u _json_key --password-stdin https://eu.gcr.io
           docker load -i ${HOME}/project/webbb_latest.tar.gz
           docker tag webbb:latest eu.gcr.io/${GOOGLE_PROJECT_ID}/webbb:${CIRCLE_SHA1}
           docker push eu.gcr.io/${GOOGLE_PROJECT_ID}/webbb:${CIRCLE_SHA1}
  deploy:
    docker:
      - image: google/cloud-sdk
        environment:
          DEPLOYMENT_NAME: webbb-app
          DEPLOYMENT_CONTAINER_NAME: webbb-app
    steps:
     - setup_remote_docker
     - run:
         name: simple deployment
         command: |
           TAG=${CIRCLE_SHA1::6}
            echo "$GCLOUD_ACC" | base64 --d > gcloud-service-key.json
            gcloud auth activate-service-account --key-file gcloud-service-key.json
            gcloud --quiet config set project $GOOGLE_PROJECT_ID
            gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
            gcloud container clusters get-credentials my-gke-cluster --region europe-west3
            kubectl set image deployment/my-gke-cluster $DEPLOYMENT_CONTAINER_NAME=eu.gcr.io/${GOOGLE_PROJECT_ID}/$DEPLOYMENT_NAME:$TAG
workflows:
  version: 2
  build_push_and_deploy:
    jobs:
      - build:
         filters:
           branches:
             only: master
      - push:
         context:
           - gcp
         requires:
           - build
      - deploy:
         context:
           - gcp
         requires:
           - build
           - push