version: 2.1
jobs:
  build:
    machine: true
    steps:
     - checkout
     - run: 
         name: build
         command: |
           docker build -t webbb .
           docker save webbb:latest | gzip > webbb_latest.tar.gz
     - persist_to_workspace:
         root: ./
         paths:
             - ./
  push:
    docker:
      - image: google/cloud-sdk
    steps:
     - attach_workspace:
         at: ./
     - run:
         name: push in gcr
         command: |
           service docker status
           sleep 5
           echo " { \"type\": \"service_account\", 
           \"private_key_id\": \"$GCLOUD_PRIVATE_KEY_ID\", 
           \"private_key\": \"$GCLOUD_SERVICE_KEY\", 
           \"client_email\": \"$GOOGLE_EMAIL\",
           \"client_id\": \"$CLIENT_ID\",
           \"auth_uri\": \"https://accounts.google.com/o/oauth2/auth\",
           \"token_uri\": \"https://oauth2.googleapis.com/token\", 
           \"auth_provider_x509_cert_url\": \"https://www.googleapis.com/oauth2/v1/certs\", 
           \"client_x509_cert_url\": \"$GCP_AUTH_X509\" } " >cred.json
           gcloud auth activate-service-account --key-file=cred.json
           gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
           gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
           cd ${HOME}/project
           docker load -i ${HOME}/project/webbb_latest.tar.gz
           docker tag webbb:latest eu.gcr.io/${GOOGLE_PROJECT_ID}/webbb:${CIRCLE_SHA1}
           docker images
           sleep 15
           gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://eu.gcr.io
           docker push eu.gcr.io/${GOOGLE_PROJECT_ID}/webbb:${CIRCLE_SHA1}
workflows:
  version: 2.1
  build_and_push:
    jobs:
      - build:
         filters:
           branches:
             only: master
      - push:
         context:
           - gcp
         requires:
           - build
