---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "address-book"
  namespace: "default"
  labels:
    app: "address-book"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "address-book"
  template:
    metadata:
      labels:
        app: "address-book"
    spec:
      containers:
      - name: "webbb-sha256-1"
        image: "eu.gcr.io/citric-earth-319117/webbb@sha256:75210fc3c3cee25b01a82512db2a25c8c62646cb9d7ceb876a57d013de598643"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "address-book-hpa-3rot"
  namespace: "default"
  labels:
    app: "address-book"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "address-book"
    apiVersion: "apps/v1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80

